import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/widgets/header/header';
import { ConvexAuthNextjsServerProvider } from '@convex-dev/auth/nextjs/server';
import { MainProvider } from '@/shared/providers/main.provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-x-hidden`}
        >
          <MainProvider>
            <Header />
            {children}
          </MainProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
